sudo: required

language: python

services: docker

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

before_install:
  - docker build -t songfortune .

install:
  - pip install -r requirements.txt

script:
  - pytest

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag songfortune benmckibben/songfortune:latest;
    docker push benmckibben/songfortune:latest;
    fi